In [2]:
! pip install numpy

^C


In [3]:
import numpy as np

In [18]:
m1 = np.array([[1, 2],
               [4, 0],
               [7, 8]])

m2 = np.array([[3, 4, 5],
               [6, 7, 8]])

sm1 = np.array([[15, 18, 21],
                [42, 51, 0],
                [69, 0, 99]])

v1 = [1, 0, 5]
v2 = [3, 6, -6]

lst1 = [1, 2, 3, 4, 5]

Ex-1 Matrix product

In [5]:
def matrix_prod(m1, m2):
    return np.matmul(m1, m2)

In [6]:
matrix_prod(m1, m2)

array([[15, 18, 21],
       [12, 16, 20],
       [69, 84, 99]])

Ex-2 Matrix outer product

In [7]:
def outer_prod(m1, m2):
    return np.outer(m1, m2)

In [8]:
outer_prod(m1, m2)

array([[ 3,  4,  5,  6,  7,  8],
       [ 6,  8, 10, 12, 14, 16],
       [12, 16, 20, 24, 28, 32],
       [ 0,  0,  0,  0,  0,  0],
       [21, 28, 35, 42, 49, 56],
       [24, 32, 40, 48, 56, 64]])

Ex-3 Vectors cross product

In [9]:
def cross_prod(v1, v2):
    return np.cross(v1, v2)

In [10]:
cross_prod(v1, v2)

array([-30,  21,   6])

Ex-4 square matrix det

In [11]:
def get_square_matrix_det(m):
    return np.linalg.det(m)

In [12]:
get_square_matrix_det(sm1)

np.float64(inf)

Ex-5 eigenvectors and eigenvalues

In [13]:
def get_eigens(m):
    return np.linalg.eig(m)

In [19]:
values, vectors = get_eigens(sm1)
print(values)
print(vectors)

[-10.51935391 115.35334829  60.16600562]
[[ 0.73263948 -0.22804792 -0.19939047]
 [-0.50018175 -0.14883472 -0.91363676]
 [-0.46158165 -0.96220703  0.35427575]]


Ex-6 Matrix_inv

In [20]:
def get_inv(m):
    return np.linalg.inv(m)

In [21]:
get_inv(sm1)

array([[-0.0691568 ,  0.02440828,  0.01466963],
       [ 0.05695266, -0.0004931 , -0.01208087],
       [ 0.0482002 , -0.01701183, -0.00012327]])

EX-7 Не один не равен нулю.

In [22]:
(sm1 == 0).sum()

np.int64(2)

Ex-8 Тест на бесконечность

In [23]:
p = np.isposinf(sm1)
n = np.isneginf(sm1)
p, n

(array([[False, False, False],
        [False, False, False],
        [False, False, False]]),
 array([[False, False, False],
        [False, False, False],
        [False, False, False]]))

Ex-9 For Complex/Real/Scalar

In [24]:
def get_props(m):
    print(f'For Complex -- {np.iscomplex(m)}, \n\nReal -- {np.real(m)}, \n\nScalar -- {np.isscalar(m)}')

In [25]:
get_props(sm1)

For Complex -- [[False False False]
 [False False False]
 [False False False]], 

Real -- [[15 18 21]
 [42 51  0]
 [69  0 99]], 

Scalar -- False


Ex-10 List to np.array

In [29]:
def list_to_vector(lst):
    return np.array(lst, dtype=float)

In [30]:
list_to_vector(lst1)

array([1., 2., 3., 4., 5.])

Ex-11 Null Vector (10) & Update Sixth Value

In [41]:
null_vec = np.zeros((10))
null_vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
null_vec[5] = 11
null_vec

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

Ex-12 Array from 12 to 38

In [44]:
vec2 = np.arange(12, 38)
vec2

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

Ex-13 Reverse array

In [47]:
vec2_res = vec2[::-1]
vec2_res

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

Ex-14 Convert Array to Float Type

In [53]:
vec2_float = np.astype([vec2, float])

TypeError: astype() missing 1 required positional argument: 'dtype'