# Что такое NumPy?

NumPy — это библиотека Python, используемая для работы с массивами.

Он также имеет функции для работы в области линейной алгебры, преобразования Фурье и матриц.

NumPy был создан в 2005 году Трэвисом Олифантом. Это проект с открытым исходным кодом, и вы можете использовать его свободно.

NumPy означает Numerical Python.

NumPy — это библиотека Python, частично написанная на Python, но большинство частей, требующих быстрых вычислений, написаны на C или C++.

# Зачем использовать NumPy?

В Python у нас есть списки, которые служат в роли массивов, но они медленно обрабатываются.

NumPy стремится предоставить объект массива, который работает до 50 раз быстрее, чем традиционные списки Python.

Объект массива в NumPy называется <b>ndarray</b>.

Массивы очень часто используются в data science, где очень важны скорость и ресурсы.

# Почему NumPy быстрее списков?

<b>list</b> - <b><i>dinamic</i></b> array

<b>ndarray</b> - <b><i>static</i></b> array

Массивы NumPy хранятся в одном непрерывном месте в памяти, в отличие от списков.

Это основная причина, по которой NumPy работает быстрее, чем списки. Также он оптимизирован для работы с последними архитектурами ЦП.

In [1]:
# ! pip install numpy
# # ! conda install numpy

In [3]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

In [37]:
# вектор
n1 = np.array([0, 1, 2, 3], dtype="float64")  # [0 1 2 3]

In [38]:
print(n1)
n1

[0. 1. 2. 3.]


array([0., 1., 2., 3.])

In [39]:
type(n1)

numpy.ndarray

In [40]:
n1.ndim  # размерность

1

In [41]:
n1.shape  # размер матрицы (1-ая цифра: кол. тензоров, 2-ая цифра: кол. строк, 3-я цифра: кол. столбцов)

(4,)

In [42]:
n1.size  # произведения цифр в n1.shape

4

In [43]:
n1.dtype  # какие типы данных в матрице

dtype('float64')

In [44]:
n1.itemsize  # количество байтов для одного элемента из n1

8

In [45]:
n1.nbytes  # количество байтов n1

32

In [50]:
# матрица
n2 = np.array([[0, 1, 2],
               [5, 1, 3.14],
               [7, 8, 7],
               [0, 12, 1]])
n2

array([[ 0.  ,  1.  ,  2.  ],
       [ 5.  ,  1.  ,  3.14],
       [ 7.  ,  8.  ,  7.  ],
       [ 0.  , 12.  ,  1.  ]])

In [51]:
print(n2.ndim)      # 2
print(n2.shape)     # (4, 3)
print(n2.size)      # 12
print(n2.dtype)     # float64
print(n2.itemsize)  # 8
print(n2.nbytes)    # 96

2
(4, 3)
12
float64
8
96


In [52]:
# тензор
n3 = np.array([[[0, 1, 2],
                [5, 1, 3],
                [5, 6, 8]],
               [[5, 7, 8],
                [7, 3, 11],
                [12, 14, 4]]
              ])
n3

array([[[ 0,  1,  2],
        [ 5,  1,  3],
        [ 5,  6,  8]],

       [[ 5,  7,  8],
        [ 7,  3, 11],
        [12, 14,  4]]])

In [54]:
print(n3.ndim)
print(n3.shape)
print(n3.size)
print(n3.dtype)
print(n3.itemsize)
print(n3.nbytes)

3
(2, 3, 3)
18
int32
4
72


In [17]:
np4 = np.zeros(5)
np5 = np.zeros((2, 2))
print(np4, end='\n\n')
print(np5)

[0. 0. 0. 0. 0.]

[[0. 0.]
 [0. 0.]]


In [18]:
np6 = np.ones((2, 3, 2))
np6

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [19]:
np7 = np.full((2, 4), 3.14)
np7

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [20]:
np8 = np.arange(10)
np9 = np.arange(1, 8.3, 0.5)
print(np8, end='\n\n')
print(np9)

[0 1 2 3 4 5 6 7 8 9]

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8. ]


In [56]:
n89 = np.arange(1, 10).reshape((3, 3))
n89

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np10 = np.linspace(0, 1, 10)
np10

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [69]:
np11 = np.linspace(0, 1, 6, endpoint=False)
np11

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333])

In [23]:
np12 = np.eye(4, 5)
print(np12, end='\n\n')

np121 = np.eye(4, 3)
print(np121, end='\n\n')

np122 = np.eye(3)
print(np122)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
np13 = np.diag(np.array([1, 2, 3, 4]))
print(np13, end='\n\n')

np15 = np.diag([1, 2, 3])
print(np15, end='\n\n')

np151 = np.diag([1, 2, 3], 2)
print(np151)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

[[1 0 0]
 [0 2 0]
 [0 0 3]]

[[0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [70]:
np.diag([[1, 2, 3], 
         [4, 5, 6], 
         [7, 8, 9]])

array([1, 5, 9])

In [71]:
np.diagflat([[1, 2, 3], 
             [4, 5, 6], 
             [7, 8, 9]])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [72]:
np14 = np.empty([2, 3])
np14

array([[0.        , 0.16666667, 0.33333333],
       [0.5       , 0.66666667, 0.83333333]])

In [33]:
np.fromiter('hello', dtype='U1')

array(['h', 'e', 'l', 'l', 'o'], dtype='<U1')

In [34]:
np.fromstring('1, 2, 3', dtype='int16', sep=',')

array([1, 2, 3], dtype=int16)

### Random

In [35]:
np.random.rand(4)

array([0.88213083, 0.58749725, 0.5657638 , 0.21273415])

In [36]:
np.random.rand(3, 2, 2)

array([[[0.84071702, 0.82516639],
        [0.27797886, 0.38877414]],

       [[0.21904323, 0.49076632],
        [0.69610627, 0.51041335]],

       [[0.20455233, 0.33543857],
        [0.06441054, 0.86733377]]])

In [37]:
np.random.random((3, 3))

array([[0.39252464, 0.35287255, 0.45301709],
       [0.5502861 , 0.70661437, 0.78227483],
       [0.21703688, 0.19751816, 0.97546889]])

In [38]:
np.random.randn(3, 2)  # samples from "standard normal" distribution

array([[-0.664336  ,  0.84456901],
       [-1.21849251, -0.71284977],
       [ 1.56732918, -0.03937888]])

In [39]:
np.random.normal(10, 5, (3, 3))

array([[ 8.85549994,  7.31351431, 20.09301927],
       [11.55617519,  9.92337626,  8.07022916],
       [10.61950309, 11.53466302,  8.16192974]])

In [74]:
np.random.randint(0, 10, (2, 2))

array([[8, 0],
       [0, 6]])

In [82]:
np.random.seed(11)
np.random.randint(10, size=(2, 3))

array([[9, 0, 1],
       [7, 1, 7]])

In [83]:
np.random.seed(11)
np.random.randint(10, size=(2, 3))

array([[9, 0, 1],
       [7, 1, 7]])

In [84]:
np.random.randint(10, size=(2, 3))

array([[2, 8, 0],
       [0, 4, 2]])

In [85]:
a = np.arange(10)
np.random.shuffle(a)
a

array([2, 7, 6, 0, 3, 9, 4, 8, 5, 1])

In [86]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.random.shuffle(a)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Data types

|Data type	    |Description|
|---|---|
|bool_	        |Boolean (True or False) stored as a byte|
|int_	        |Default integer type (same as C long; normally either int64 or int32)|
|intc	        |Identical to C int (normally int32 or int64)|
|intp	        |Integer used for indexing (same as C ssize_t; normally either int32 or int64)|
|int8	        |Byte (-128 to 127)|
|int16	        |Integer (-32768 to 32767)|
|int32	        |Integer (-2147483648 to 2147483647)|
|int64	        |Integer (-9223372036854775808 to 9223372036854775807)|
|uint8	        |Unsigned integer (0 to 255)|
|uint16	        |Unsigned integer (0 to 65535)|
|uint32	        |Unsigned integer (0 to 4294967295)|
|uint64	        |Unsigned integer (0 to 18446744073709551615)|
|float_	        |Shorthand for float64.|
|float16	    |Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
|float32	    |Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
|float64	    |Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
|complex_	    |Shorthand for complex128.|
|complex64	    |Complex number, represented by two 32-bit floats|
|complex128	    |Complex number, represented by two 64-bit floats|

In [46]:
# np.sctypeDict

In [47]:
print(np.ones(10, dtype='int32'), end='\n\n')

print(np.ones(10, dtype='bool'))

[1 1 1 1 1 1 1 1 1 1]

[ True  True  True  True  True  True  True  True  True  True]


In [48]:
dt = 'int8'

print(np.array([0, 1, 2.5, 3, -4, 1_000_000.45], dtype=dt))

np.zeros(10, dtype=dt).itemsize

[ 0  1  2  3 -4 64]


1

In [49]:
a = np.array([0, 1, 2.5, 3, -4, 1_000_000.45], 'float32')

In [50]:
a = np.int32(a)
a, a.dtype

(array([      0,       1,       2,       3,      -4, 1000000]), dtype('int32'))

In [51]:
a = np.array([1, 2, 1.5, 'hello'])
a.dtype

dtype('<U32')

### Slicing, array changing

In [4]:
m = np.random.randint(1, 100, (7, 8))
m

array([[77,  1, 63, 53, 14, 84, 56, 19],
       [49, 85, 36, 82, 82, 67, 25, 37],
       [85, 74, 84, 65, 12, 33, 84, 22],
       [43, 79, 26, 85, 53, 62,  7, 35],
       [13, 80, 29, 94, 30, 58, 17, 54],
       [92,  8, 69, 31, 12, 25, 82, 88],
       [78, 96, 26, 22, 61, 85, 58, 15]], dtype=int32)

In [98]:
m[2:4, 5] = np.array([0, 0])
m

array([[ 2,  4,  9, 88, 82, 69, 73, 33],
       [79, 20, 26, 91, 39, 60, 18, 44],
       [19, 49, 11, 48, 33,  0, 41,  9],
       [69, 34,  2, 96, 76,  0, 73, 20],
       [97, 85, 51, 83, 60, 73, 39, 40],
       [35, 32,  5, 29, 14, 58, 66, 91],
       [86, 21, 18, 82, 63,  5, 75, 40]])

In [52]:
a = np.arange(10)
print(type(a), a)
print(a[0], a[5])
print(a[6::2])

<class 'numpy.ndarray'> [0 1 2 3 4 5 6 7 8 9]
0 5
[6 8]


In [53]:
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [54]:
a1 = [11, 12, 13, 14]
a[6:] = a1[::-1]  # must have same shape
a

array([ 0,  1,  2,  3,  4, 10, 14, 13, 12, 11])

In [55]:
b = np.diag(np.arange(3))
print(b)
b[1, 1]  # вторая строка, второй столбец


[[0 0 0]
 [0 1 0]
 [0 0 2]]


1

In [56]:
b[2, 1] = 15
b

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 15,  2]])

In [57]:
b[1:]

array([[ 0,  1,  0],
       [ 0, 15,  2]])

In [58]:
b[:2, :2]

array([[0, 0],
       [0, 1]])

In [59]:
b1 = b[:2, :2]
np.may_share_memory(b, b1)  # проверяет занимают ли b и b1 одинаковый блок памяти

True

In [60]:
b1_ = b1
np.may_share_memory(b1_, b1)

True

In [61]:
b1copy = b1.copy()
np.may_share_memory(b1copy, b1)

False

### Change shape

In [99]:
r = np.arange(1, 7)
r1 = np.arange(1, 7).reshape((2, 3))
r1

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
r2 = r1.flatten()
r2

array([1, 2, 3, 4, 5, 6])

In [101]:
r3 = r2.reshape((3, 2))
r3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
r

array([1, 2, 3, 4, 5, 6])

In [103]:
r[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6]])

In [104]:
print(r[np.newaxis, :])
print(r[:, np.newaxis])

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [105]:
print(r[None, :])
print(r[:, None])

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### Concatenate

In [106]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x + y

array([5, 7, 9])

In [107]:
np.concatenate((x, y))

array([1, 2, 3, 4, 5, 6])

In [108]:
z = np.array([[7, 8, 9],
              [10, 11, 12]])

np.concatenate([z, z], axis=0)  # как отдельная матрица добавить, по умолчанию axis=0

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
np.concatenate([z, z], axis=1)  # добавить, как продолжение строк

array([[ 7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12]])

In [72]:
np.vstack([x, z])  # добавляет снизу

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
p = np.array([[2, 4],
              [3, 5]])

np.hstack([p, z])  # добавляет справа

array([[ 2,  4,  7,  8,  9],
       [ 3,  5, 10, 11, 12]])

In [74]:
np.hstack((x, y))

array([1, 2, 3, 4, 5, 6])

In [75]:
np.vstack((x, y))

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
np.column_stack((x, y))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
np.row_stack((x, y))

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
np.dstack((x, y))  # добавляет тензор

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [79]:
np.r_[[1, 2, 3], 4, 5]

array([1, 2, 3, 4, 5])

In [80]:
np.r_[1:10, 100, 200]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100, 200])

In [81]:
np.r_[ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9]] ]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.c_[1:10]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [83]:
np.c_[[1, 2, 3], [4, 5, 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

### Split

In [84]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
x1, x2, x3, x4 = np.split(x, (2, 5, 8))

x1, x2, x3, x4

(array([1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10]))

In [85]:
z = np.arange(1, 17).reshape((4, 4))
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [86]:
z1, z2 = np.vsplit(z, [3])
z3, z4 = np.hsplit(z, [2])

print(z1, '\n\n', z2, '\n\n', z3, '\n\n', z4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[13 14 15 16]] 

 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]] 

 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


### list VS ndarray

In [127]:
def reciprocals_1(x):
    return 1 / np.array(x)

x = [2, 10, 5, 4]
reciprocals_1(x)

array([0.5 , 0.1 , 0.2 , 0.25])

In [128]:
import time

In [129]:
big_array = np.random.randint(1, 100, size=100_000_000)

In [130]:
start = time.time()
reciprocals_1(big_array)
time_array = time.time() - start 
print("%s seconds" % time_array)

0.7976984977722168 seconds


In [131]:
def reciprocals_2(x):
    a = []
    for i in range(len(x)):
        a.append(1 / x[i])
    return a

x = [2, 10, 5, 4]
reciprocals_2(x)

[0.5, 0.1, 0.2, 0.25]

In [134]:
big_array.dtype

dtype('int32')

In [132]:
start = time.time()
reciprocals_2(big_array)
time_list = time.time() - start
print("%s seconds" % time_list)

28.993205070495605 seconds


In [137]:
time_list / time_array

36.346069538135986

### Padding

In [102]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
np.pad(a, 1)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

In [104]:
np.pad(a, ((1, 2), (3, 4)))  # ((up, down), (left, right))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 5, 6, 0, 0, 0, 0],
       [0, 0, 0, 7, 8, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [105]:
np.pad(a, pad_width=1, mode='constant', constant_values=((10, 20), (30, 40)))

array([[30, 10, 10, 10, 40],
       [30,  1,  2,  3, 40],
       [30,  4,  5,  6, 40],
       [30,  7,  8,  9, 40],
       [30, 20, 20, 20, 40]])

In [106]:
# mode = 'constant', 'minimun', 'maximum', 'mean', 'median', 'edge', 'symmetric', 'reflect', 'empty', etc.

In [107]:
np.pad(a, pad_width=2, mode='reflect', reflect_type='odd')

array([[-7, -6, -5, -4, -3, -2, -1],
       [-4, -3, -2, -1,  0,  1,  2],
       [-1,  0,  1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12, 13, 14],
       [11, 12, 13, 14, 15, 16, 17]])

In [108]:
np.pad(a, pad_width=1, mode="edge")

array([[1, 1, 2, 3, 3],
       [1, 1, 2, 3, 3],
       [4, 4, 5, 6, 6],
       [7, 7, 8, 9, 9],
       [7, 7, 8, 9, 9]])

### Unique

In [138]:
a = np.array([1, 3, 2, 3, 4, 4, 5, 2, 3, 1, 5, 4, 2, 2])
a

array([1, 3, 2, 3, 4, 4, 5, 2, 3, 1, 5, 4, 2, 2])

In [139]:
np.unique(a)

array([1, 2, 3, 4, 5])

In [140]:
np.unique(a, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 4, 3, 3, 2], dtype=int64))

In [112]:
np.unique(a, return_index=True)

(array([1, 2, 3, 4, 5]), array([0, 2, 1, 4, 6], dtype=int64))

In [113]:
np.unique(a, return_inverse=True)

(array([1, 2, 3, 4, 5]),
 array([0, 2, 1, 2, 3, 3, 4, 1, 2, 0, 4, 3, 1, 1], dtype=int64))

In [114]:
s, ind = np.unique(a, return_inverse=True)
a_new = s[ind]
a_new

array([1, 3, 2, 3, 4, 4, 5, 2, 3, 1, 5, 4, 2, 2])

In [115]:
x = np.array([[0, 1, 1, 2], [0, 1, 1, 2], [9, 1, 1, 2], ])
print(x, np.unique(x), np.unique(x, axis=0), np.unique(x, axis=1), sep='\n\n')

[[0 1 1 2]
 [0 1 1 2]
 [9 1 1 2]]

[0 1 2 9]

[[0 1 1 2]
 [9 1 1 2]]

[[0 1 2]
 [0 1 2]
 [9 1 2]]


In [116]:
a = np.array([0, 1, 2, 3, 2])
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 1, 6])

np.in1d(a, b)

array([False,  True,  True,  True,  True])

In [117]:
np.intersect1d(a, b)

array([1, 2, 3])

In [118]:
np.union1d(a, b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
np.setdiff1d(a, b), np.setdiff1d(b, a)

(array([0]), array([4, 5, 6, 7, 8]))

In [120]:
np.setxor1d(a, b)

array([0, 4, 5, 6, 7, 8])

### Operations on ndarray

|Operator	|Equivalent ufunc|	    Description|
|---|---|---|
|+	        |np.add	         |       Addition (e.g., 1 + 1 = 2)|
|-	        |np.subtract	 |           Subtraction (e.g., 3 - 2 = 1)|
|-	        |np.negative	 |           Unary negation (e.g., -2)|
|*	        |np.multiply	 |           Multiplication (e.g., 2 * 3 = 6)|
|/	        |np.divide	     |       Division (e.g., 3 / 2 = 1.5)|
|//	        |np.floor_divide	|        Floor division (e.g., 3 // 2 = 1)|
|**	        |np.power	     |       Exponentiation (e.g., 2 ** 3 = 8)|
|%	        |np.mod	         |       Modulus/remainder (e.g., 9 % 4 = 1)|

In [143]:
x = np.arange(9).reshape((3, 3))

print(x, end='\n\n')
print(x ** 2, end='\n\n')
print(x + 5, end='\n\n')
print(x - 5, end='\n\n')
print(x * 2, end='\n\n')
print(x / 2, end='\n\n')
print(x // 2, end='\n\n')
print(x % 2, end='\n\n')
print(x * x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]

[[0 0 1]
 [1 2 2]
 [3 3 4]]

[[0 1 0]
 [1 0 1]
 [0 1 0]]

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [144]:
a = np.array([1, 2, 3])
a / 0

C:\Users\user\AppData\Local\Temp\ipykernel_26212\1937119386.py:2: RuntimeWarning: divide by zero encountered in divide
  a / 0


array([inf, inf, inf])

In [123]:
print(np.e)  # число e
print(np.pi)  # число П
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
print(np.tan(np.pi/4))
print(np.arcsin(1))
print(np.arccos(1))
print(np.arctan(0))

2.718281828459045
3.141592653589793
0.49999999999999994
0.5000000000000001
0.9999999999999999
1.5707963267948966
0.0
0.0


In [145]:
x = [2, 0, 1]

print(np.exp(x))  # e^x
print(np.exp2(x))  # 2^x
print(np.power(3, x))  # 3^x and x>0

[7.3890561  1.         2.71828183]
[4. 1. 2.]
[9 1 3]


In [125]:
y = [1, np.e, 4, 10, 100]

print(np.log(y))     # ln(y)
print(np.log2(y))    # log2(y)
print(np.log10(y))   # log10(y)

[0.         1.         1.38629436 2.30258509 4.60517019]
[0.         1.44269504 2.         3.32192809 6.64385619]
[0.         0.43429448 0.60205999 1.         2.        ]


In [126]:
L = np.random.random(100)
print("Python sum : ", sum(L))
print("NumPy sum : ", np.sum(L))

Python sum :  47.87653997080133
NumPy sum :  47.87653997080132


In [127]:
big_array = np.random.rand(100000000)

start = time.time()
sum(big_array)
print("%s seconds" % (time.time() - start))

start = time.time()
np.sum(big_array)
print("%s seconds" % (time.time() - start))

5.706163644790649 seconds
0.09374117851257324 seconds


In [128]:
z = np.arange(16).reshape((4, 4))
print(z)
print(np.min(z), np.max(z))
print(z.min(), z.max(), z.sum())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
0 15
0 15 120


In [129]:
print(z.min(axis=0))  # по столбцам
print(z.min(axis=1))  # по строкам
print(z.mean(axis=0))  # среднее значение по столбцам
print(z.mean(axis=1))  # среднее значение по строкам
print(z.sum(axis=0))  # сумма элементов по столбцам
print(z.sum(axis=1))  # сумма элементов по строкам
print(z.sum())  # сумма всех элементов

[0 1 2 3]
[ 0  4  8 12]
[6. 7. 8. 9.]
[ 1.5  5.5  9.5 13.5]
[24 28 32 36]
[ 6 22 38 54]
120


In [165]:
m = np.arange(1, 21, dtype="int64").reshape((4, 5))
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int64)

In [166]:
m.sum(), np.sum(m)

(210, 210)

In [167]:
m.sum(axis=0)

array([34, 38, 42, 46, 50], dtype=int64)

In [168]:
m.sum(axis=1)

array([15, 40, 65, 90], dtype=int64)

In [169]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int64)

In [170]:
m.prod(axis=1)

array([    120,   30240,  360360, 1860480], dtype=int64)

In [171]:
m.prod()

2432902008176640000

In [172]:
import math
math.prod([120, 30240, 360360, 1860480])

2432902008176640000

In [174]:
m.max(axis=1)

array([ 5, 10, 15, 20], dtype=int64)

In [175]:
m.max(axis=1)

array([ 5, 10, 15, 20], dtype=int64)

In [182]:
x = np.array([9, 12, 6, 7, 2, 6, 17, 4, -10, 5, 11, -1, 1, 1, 14])
y = np.array([6, 17, 3, 24, 3, 10, 8, 12, -8, 0, 8, 1, 1, 36, 8])

In [183]:
np.median(x), np.median(y)

(6.0, 8.0)

In [132]:
np.var(x), np.var(y)

(41.97333333333333, 107.17333333333333)

In [133]:
np.std(x), np.std(y)

(6.478682993736715, 10.352455425324628)

In [134]:
np.cov(x, y)

array([[ 44.97142857,  20.54285714],
       [ 20.54285714, 114.82857143]])

In [135]:
np.corrcoef(x, y)

array([[1.       , 0.2858693],
       [0.2858693, 1.       ]])

### numpy.nan

In [184]:
n = np.array([[1, 5, np.nan],
              [3, np.nan, 0]])

In [185]:
n.sum()

nan

In [186]:
 np.nansum(n), np.nanmin(n), np.nanmax(n)

(9.0, 0.0, 5.0)

|Function Name	    |NaN-safe Version	    |Description|
|---|---|---|
|np.sum	            |np.nansum	            |Compute sum of elements|
|np.prod	        |    np.nanprod	        |    Compute product of elements|
|np.mean	        |    np.nanmean	        |    Compute mean of elements|
|np.std	            |np.nanstd	            |Compute standard deviation|
|np.var	            |np.nanvar	            |Compute variance|
|np.min	            |np.nanmin	            |Find minimum value|
|np.max	            |np.nanmax	            |Find maximum value|
|np.argmin	        |np.nanargmin	        |Find index of minimum value|
|np.argmax	        |np.nanargmax	        |Find index of maximum value|
|np.median	        |np.nanmedian	        |Compute median of elements|
|np.percentile	    |np.nanpercentile	    |Compute rank-based statistics of elements|
|np.any	            |N/A	                |    Evaluate whether any elements are true|
|np.all	            |N/A	                |    Evaluate whether all elements are true|


### Shapes

1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

  (3 x 1) + (1 x 0) = (3 x 1)


2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
  
  (3 x 3) + (1 x 3) = (3 x 3)
  
  (1 x 3) + (1 x 3) = (3 x 3)


3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [139]:
m = np.ones((2, 3))
a = np.arange(3)

print(m, end='\n\n')
print(a, end='\n\n')
print(m + a)

[[1. 1. 1.]
 [1. 1. 1.]]

[0 1 2]

[[1. 2. 3.]
 [1. 2. 3.]]


In [140]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

print(a, end='\n\n')
print(b, end='\n\n')
print(a + b)

[[0]
 [1]
 [2]]

[0 1 2]

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [141]:
m = np.ones((3, 2))
a = np.arange(3)

print(m, end='\n\n')
print(a, end='\n\n')
print(m + a)  # error

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[0 1 2]



ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

### Logical operators

In [188]:
x = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 5, 4]])

print(x < 3, end='\n\n')
print((x == 3) * 1, end='\n\n')
print((2 * x) == (x ** 2))

[[ True  True False False False]
 [False False False False False]]

[[0 0 1 0 0]
 [0 0 0 0 0]]

[[False  True False False False]
 [False False False False False]]


In [189]:
x[x>3]

array([4, 5, 4, 5, 6, 5, 4])

In [203]:
m = np.random.randint(1, 100, (5, 6))
m

array([[13,  4, 24, 74, 78, 43],
       [98,  6, 82, 81, 28, 91],
       [96,  3, 55, 84, 30, 45],
       [55, 97, 87,  5, 34, 14],
       [95, 14, 57, 93, 82, 81]])

In [204]:
m[(m>=90) | (m<=10)]

array([ 4, 98,  6, 91, 96,  3, 97,  5, 95, 93])

In [207]:
m[[0, 4, 1, 3, 2]]

array([[13,  4, 24, 74, 78, 43],
       [95, 14, 57, 93, 82, 81],
       [98,  6, 82, 81, 28, 91],
       [55, 97, 87,  5, 34, 14],
       [96,  3, 55, 84, 30, 45]])

In [209]:
m[:, ::-1]

array([[43, 78, 74, 24,  4, 13],
       [91, 28, 81, 82,  6, 98],
       [45, 30, 84, 55,  3, 96],
       [14, 34,  5, 87, 97, 55],
       [81, 82, 93, 57, 14, 95]])

In [211]:
m[:, [0, 5]]

array([[13, 43],
       [98, 91],
       [96, 45],
       [55, 14],
       [95, 81]])

|Operator	|Equivalent ufunc|
|---|---|
|==	        |np.equal|
|<	        |np.less|
|>	        |np.greater|
|!=	        |np.not_equal|
|<=	        |np.less_equal|
|>=	        |np.greater_equal|

### Take elements from array

In [144]:
x = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])

x[row, col]

array([ 2,  5, 11])

In [146]:
print(x[2, [2, 0, 1]])
print(x[1:, [2, 0, 1]])

[10  8  9]
[[ 6  4  5]
 [10  8  9]]


### Sort

In [147]:
n = np.array([5, -1, 4, 3, 54, 12, -5, 0, 1, 41])
print(np.sort(n))
print(np.argsort(n))
print(np.argmin(n))
print(np.argmax(n))

[-5 -1  0  1  3  4  5 12 41 54]
[6 1 7 8 3 2 0 5 9 4]
6
4


# Matrices

In [148]:
x = np.random.randint(0, 10, (2, 3))
x

array([[8, 6, 0],
       [4, 8, 0]])

In [149]:
print(x.T, end='\n\n')
print(x.transpose())

[[8 4]
 [6 8]
 [0 0]]

[[8 4]
 [6 8]
 [0 0]]


In [150]:
a = np.array([2, 0, 3])

print(np.expand_dims(a, axis=0), np.expand_dims(a, axis=1), sep='\n\n')

[[2 0 3]]

[[2]
 [0]
 [3]]


In [151]:
a = np.array([[2, 0, 3]])

print(np.squeeze(a, axis=0))

[2 0 3]


In [152]:
a = np.array([[2, 3, 1],
              [3, -1, 0]])

b = np.array([[1, -3],
              [4, 0],
              [2, -2]])

c = np.array([[2, 0, 4, 5, -9],
              [1, 4, 3, 8, -2]])

print('First method', a.dot(b), sep='\n', end='\n\n')
print('Second method', np.matmul(a, b), sep='\n', end='\n\n')
print('The shortest method', a @ b, sep='\n')

First method
[[16 -8]
 [-1 -9]]

Second method
[[16 -8]
 [-1 -9]]

The shortest method
[[16 -8]
 [-1 -9]]


In [153]:
# product
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])

print(x, y, sep='\n\n', end='\n\n')

print('Method 1:', np.dot(x, y), sep='\n', end='\n\n')
print('Method 2:', np.matmul(x, y), sep='\n', end='\n\n')
print('Method 3:', np.inner(x, y), sep='\n', end='\n\n')
print('Method 4:', np.outer(x, y), sep='\n', end='\n\n')
print('Method 5 = Method 2:', x @ y, sep='\n', end='\n\n')

[1 2 3]

[2 3 4]

Method 1:
20

Method 2:
20

Method 3:
20

Method 4:
[[ 2  3  4]
 [ 4  6  8]
 [ 6  9 12]]

Method 5 = Method 2:
20



In [154]:
# Inverse matrix

d = np.array([[3, 2, 3],
              [1, 3, 4],
              [3, 4, 5]])

d_inv = np.linalg.inv(d)

print('Inverse Matrix:\n', d_inv, end='\n\n')
print('Checking the inverse d_inv * d:\n', np.around(d_inv @ d), end='\n\n')
print('Checking the inverse d * d_inv:\n', abs(np.around(d @ d_inv)))

Inverse Matrix:
 [[ 0.25 -0.5   0.25]
 [-1.75 -1.5   2.25]
 [ 1.25  1.5  -1.75]]

Checking the inverse d_inv * d:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Checking the inverse d * d_inv:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [155]:
identity_matrix = np.eye(3)

print(identity_matrix, end='\n\n')

print(a @ identity_matrix, end='\n\n')
print(a @ identity_matrix == a, end='\n\n')

print('Checking the equality of arrays (method 1):',
      (a @ identity_matrix == a).all())

print('Checking the equality of arrays (method 2):',
      np.allclose(a @ identity_matrix, a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 2.  3.  1.]
 [ 3. -1.  0.]]

[[ True  True  True]
 [ True  True  True]]

Checking the equality of arrays (method 1): True
Checking the equality of arrays (method 2): True


In [156]:
# Norm
x = np.array([4, 3])
print('First Method', np.linalg.norm(x))
print('Second Method', np.sqrt(x @ x.T))

First Method 5.0
Second Method 5.0


In [158]:
A = np.array([[1, -3, 2],
              [4, -1, 2],
              [3, 5, 2]])

# Детерминант матрицы
print('det(A) =', np.linalg.det(A))

# След матрицы
print('Tr(A) = ', np.trace(A))
print('Tr(A) = ', np.sum(np.diag(A)))

# Ранг матрицы
print('Rank(A) =', np.linalg.matrix_rank(A))

# Степень матрицы
print('A ^ 2 =', np.linalg.matrix_power(A, 2))

det(A) = 40.0
Tr(A) =  2
Tr(A) =  2
Rank(A) = 3
A ^ 2 = [[-5 10  0]
 [ 6 -1 10]
 [29 -4 20]]


In [159]:
# solving a*x=b linear equation

a = np.array([[3, 1],
              [1, 2]])

b = np.array([9, 8])

x = np.linalg.solve(a, b)
print(x, end='\n\n')

# checking the solution
print(np.allclose(a @ x, b))
print(a @ x)

[2. 3.]

True
[9. 8.]


In [160]:
A = np.array([[2, 0, 3],
              [0, 3, 1],
              [0, 0, 4]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print('Eigenvalues:', eigenvalues)
print('Eigenvectors as columns:\n', eigenvectors)
print(np.linalg.eigvals(A))

# checking the above
print('det(A) = ', np.linalg.det(A))
print('det(A) = ', np.prod(eigenvalues))
print('Tr(A) = ', np.sum(eigenvalues))
print('Tr(A) = ', np.trace(A))

Eigenvalues: [2. 3. 4.]
Eigenvectors as columns:
 [[1.         0.         0.72760688]
 [0.         1.         0.48507125]
 [0.         0.         0.48507125]]
[2. 3. 4.]
det(A) =  23.999999999999993
det(A) =  24.0
Tr(A) =  9.0
Tr(A) =  9


In [161]:
# Eigendecomposition
D = np.diag(eigenvalues)
print(eigenvectors @ D @ np.linalg.inv(eigenvectors))

[[2. 0. 3.]
 [0. 3. 1.]
 [0. 0. 4.]]


In [162]:
# Cholesky Decomposition
A = np.array([[2, 1],
              [1, 4]])

L = np.linalg.cholesky(A)
print(L, end='\n\n')

print('A = L * L^T:', np.allclose(A, L @ L.T))
print(L @ L.T)

[[1.41421356 0.        ]
 [0.70710678 1.87082869]]

A = L * L^T: True
[[2. 1.]
 [1. 4.]]


In [163]:
# Singular Value Decomposition
A = np.array([[1, 2, 3],
              [4, 5, 6]])

u, s, vh = np.linalg.svd(A)

print('u:', u.shape, u, sep='\n', end='\n\n')
print('s:', s.shape, s, sep='\n', end='\n\n')
print('vh:', vh.shape, vh, sep='\n', end='\n\n')

S = np.hstack((np.diag(s), np.zeros((2, 1))))
print(S)
print(u @ S @ vh)

u:
(2, 2)
[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

s:
(2,)
[9.508032   0.77286964]

vh:
(3, 3)
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]

[[9.508032   0.         0.        ]
 [0.         0.77286964 0.        ]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [212]:
m = np.array([[5, 6, 3],
              [-1, 0, 1],
              [1, 2, -1]])

In [213]:
np.linalg.det(m)

-15.999999999999991

In [218]:
np.abs(np.round(np.linalg.inv(m) @ m, 10))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [219]:
eigvals, eigvects = np.linalg.eig(m)

In [220]:
eigvals

array([-2.,  4.,  2.])

In [221]:
eigvects

array([[-3.15975012e-16, -9.70494959e-01, -8.94427191e-01],
       [-4.47213595e-01,  2.15665546e-01,  4.47213595e-01],
       [ 8.94427191e-01, -1.07832773e-01, -3.18938141e-16]])

In [228]:
(eigvects[:, 0] ** 2).sum() ** 0.5

1.0

In [5]:
(m == 0).sum()

np.int64(0)